// Cross-language validation: C++ IncrementalRREF::add_columns vs Python reference.
//
// Reads rref_batch_test_cases.txt (generated by generate_rref_batch_test_cases.py),
// replays every ADD_BATCH operation using the C++ IncrementalRREF::add_columns,
// and asserts that n_checks, n_bits, pivot_map, s_prime, Z, and is_valid()
// match the Python IncrementalRREFBatch reference values exactly.
//
// The file format extends the one used by test_rref_vs_python.cpp:
//   ADD       <len> <bytes>                     — add_column (no new rows)
//   ADD_EXTRA <len> <bytes> <s_len> <s_bytes>  — add_column with new rows
//   ADD_BATCH <k>  <len0> <bytes0> ... <lenk-1> <bytesk-1>
//             SEXTRA <n> <s_bytes> | NO_SEXTRA  — add_columns (k columns)
//
// Build (from the src/ directory):
//   g++ -std=c++17 -O2 -mavx2 -Wall \
//       test_accross_python_cplus/test_rref_batch_vs_python.cpp \
//       incremental_rref.cpp gf2matrix.cpp \
//       -o test_rref_batch_cross
//   ./test_rref_batch_cross [path/to/rref_batch_test_cases.txt]
// Default path: test_accross_python_cplus/rref_batch_test_cases.txt

#include "../incremental_rref.hpp"

#include <cassert>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Parsing helpers
// ---------------------------------------------------------------------------

static std::vector<uint8_t> parse_bytes(std::istringstream& ss, int n)
{
    std::vector<uint8_t> v(n);
    for (int i = 0; i < n; ++i) {
        int x; ss >> x;
        v[i] = static_cast<uint8_t>(x);
    }
    return v;
}

// ---------------------------------------------------------------------------
// Apply one operation line (keyword already consumed from ss).
// ---------------------------------------------------------------------------

static void apply_op(const std::string& keyword,
                     std::istringstream& ss,
                     IncrementalRREF& rref)
{
    if (keyword == "ADD") {
        int h_len; ss >> h_len;
        rref.add_column(parse_bytes(ss, h_len));

    } else if (keyword == "ADD_EXTRA") {
        int h_len; ss >> h_len;
        auto h = parse_bytes(ss, h_len);
        int s_len; ss >> s_len;
        rref.add_column(h, parse_bytes(ss, s_len));

    } else if (keyword == "ADD_BATCH") {
        // ADD_BATCH <k>  <len0> <bytes0>  ...  SEXTRA <n> <s_bytes> | NO_SEXTRA
        int k; ss >> k;

        std::vector<std::vector<uint8_t>> columns(k);
        for (int j = 0; j < k; ++j) {
            int len; ss >> len;
            columns[j] = parse_bytes(ss, len);
        }

        std::string sextra_kw; ss >> sextra_kw;
        if (sextra_kw == "SEXTRA") {
            int s_len; ss >> s_len;
            auto s_ex = parse_bytes(ss, s_len);
            rref.add_columns(columns, &s_ex);
        } else {
            // "NO_SEXTRA"
            rref.add_columns(columns, nullptr);
        }

    } else {
        throw std::runtime_error("Unknown op keyword: " + keyword);
    }
}

// ---------------------------------------------------------------------------
// Expected state read from the text file.
// ---------------------------------------------------------------------------

struct ExpectedState {
    int n_checks = 0;
    int n_bits   = 0;
    std::vector<int>     pivot_map;
    std::vector<uint8_t> s_prime;
    std::vector<std::vector<uint8_t>> Z;
    int is_valid = 0;
};

// ---------------------------------------------------------------------------
// Compare C++ RREF state against expected values; abort with message on fail.
// ---------------------------------------------------------------------------

static void check_state(const std::string& name,
                        const IncrementalRREF& rref,
                        const ExpectedState& exp)
{
    auto fail = [&](const char* field, const std::string& detail = "") {
        fprintf(stderr, "FAIL [%s] %s%s\n",
                name.c_str(), field, detail.c_str());
        std::abort();
    };

    if (rref.n_checks != exp.n_checks)
        fail("n_checks",
             ": got=" + std::to_string(rref.n_checks) +
             " exp=" + std::to_string(exp.n_checks));

    if (rref.n_bits != exp.n_bits)
        fail("n_bits",
             ": got=" + std::to_string(rref.n_bits) +
             " exp=" + std::to_string(exp.n_bits));

    if ((int)rref.pivot_map.size() != rref.n_checks)
        fail("pivot_map.size() != n_checks");

    for (int i = 0; i < rref.n_checks; ++i) {
        if (rref.pivot_map[i] != exp.pivot_map[i]) {
            fail("pivot_map",
                 "[" + std::to_string(i) + "]: got=" +
                 std::to_string(rref.pivot_map[i]) + " exp=" +
                 std::to_string(exp.pivot_map[i]));
        }
    }

    for (int i = 0; i < rref.n_checks; ++i) {
        if (rref.s_prime[i] != exp.s_prime[i]) {
            fail("s_prime",
                 "[" + std::to_string(i) + "]: got=" +
                 std::to_string((int)rref.s_prime[i]) + " exp=" +
                 std::to_string((int)exp.s_prime[i]));
        }
    }

    if ((int)rref.Z.size() != (int)exp.Z.size())
        fail("|Z|",
             ": got=" + std::to_string(rref.Z.size()) +
             " exp=" + std::to_string(exp.Z.size()));

    for (int k = 0; k < (int)exp.Z.size(); ++k) {
        if (rref.Z[k].size() != exp.Z[k].size()) {
            fail("Z[k].size()",
                 ": k=" + std::to_string(k) +
                 " got=" + std::to_string(rref.Z[k].size()) +
                 " exp=" + std::to_string(exp.Z[k].size()));
        }
        for (int j = 0; j < (int)exp.Z[k].size(); ++j) {
            if (rref.Z[k][j] != exp.Z[k][j]) {
                fail("Z",
                     "[" + std::to_string(k) + "][" + std::to_string(j) + "]"
                     ": got=" + std::to_string((int)rref.Z[k][j]) +
                     " exp=" + std::to_string((int)exp.Z[k][j]));
            }
        }
    }

    int got_v = rref.is_valid() ? 1 : 0;
    if (got_v != exp.is_valid)
        fail("is_valid",
             ": got=" + std::to_string(got_v) +
             " exp=" + std::to_string(exp.is_valid));
}

// ---------------------------------------------------------------------------
// Per-test specification.
// ---------------------------------------------------------------------------

struct TestSpec {
    std::string name;
    std::vector<std::pair<std::string, std::string>> ops;   // (kw, rest_of_line)
    ExpectedState exp;
};

// ---------------------------------------------------------------------------
// Parse the test-case file.
// ---------------------------------------------------------------------------

static std::vector<TestSpec> parse_file(const std::string& path)
{
    std::ifstream fin(path);
    if (!fin) {
        fprintf(stderr, "Cannot open %s\n", path.c_str());
        std::exit(1);
    }

    std::vector<TestSpec> specs;
    TestSpec* cur = nullptr;
    bool reading_exp = false;
    int  z_remaining = 0;

    std::string line;
    while (std::getline(fin, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream ss(line);
        std::string kw; ss >> kw;

        if (kw == "TEST") {
            specs.emplace_back();
            cur          = &specs.back();
            reading_exp  = false;
            z_remaining  = 0;
            ss >> cur->name;
            continue;
        }
        if (!cur) continue;
        if (kw == "ENDTEST") { cur = nullptr; continue; }

        // ------------------------------------------------------------------
        // Expected-state block (starts at NCHECKS, ends after ISVALID)
        // ------------------------------------------------------------------
        if (kw == "NCHECKS") {
            reading_exp = true;
            ss >> cur->exp.n_checks;
            cur->exp.pivot_map.assign(cur->exp.n_checks, -1);
            cur->exp.s_prime.assign(cur->exp.n_checks, 0);
            continue;
        }
        if (reading_exp) {
            if (kw == "NBITS") {
                ss >> cur->exp.n_bits;
            } else if (kw == "PIVOT_MAP") {
                for (int i = 0; i < cur->exp.n_checks; ++i)
                    ss >> cur->exp.pivot_map[i];
            } else if (kw == "SPRIME") {
                for (int i = 0; i < cur->exp.n_checks; ++i) {
                    int v; ss >> v;
                    cur->exp.s_prime[i] = static_cast<uint8_t>(v);
                }
            } else if (kw == "ZCOUNT") {
                ss >> z_remaining;
            } else if (kw == "Z") {
                std::vector<uint8_t> z(cur->exp.n_bits);
                for (int j = 0; j < cur->exp.n_bits; ++j) {
                    int v; ss >> v;
                    z[j] = static_cast<uint8_t>(v);
                }
                cur->exp.Z.push_back(std::move(z));
                --z_remaining;
            } else if (kw == "ISVALID") {
                ss >> cur->exp.is_valid;
                reading_exp = false;
            }
            continue;
        }

        // ------------------------------------------------------------------
        // OP lines
        // ------------------------------------------------------------------
        if (kw == "OP") {
            std::string rest;
            std::getline(ss, rest);
            std::string op_kw;
            {
                std::istringstream tmp(rest);
                tmp >> op_kw;
            }
            cur->ops.push_back({op_kw, rest});
        }
    }

    return specs;
}

// ---------------------------------------------------------------------------
// Run all tests.
// ---------------------------------------------------------------------------

static int run_tests(const std::string& path)
{
    auto specs = parse_file(path);
    printf("Running %zu tests from %s\n", specs.size(), path.c_str());

    int n_passed = 0;
    for (auto& spec : specs) {
        IncrementalRREF rref;

        for (auto& [op_kw, rest] : spec.ops) {
            std::istringstream ls(rest);
            std::string kw; ls >> kw;
            apply_op(kw, ls, rref);
        }

        check_state(spec.name, rref, spec.exp);
        rref.verify();

        printf("  PASSED: %s\n", spec.name.c_str());
        ++n_passed;
    }

    return n_passed;
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

int main(int argc, char** argv)
{
    std::string path = "test_accross_python_cplus/rref_batch_test_cases.txt";
    if (argc >= 2) path = argv[1];

    int n_passed = run_tests(path);
    printf("\nAll %d tests passed.\n", n_passed);
    return 0;
}
