// Cross-language validation: C++ ClusteringOvgBatch vs Python ClusteringOvergrowBatch.
//
// Reads clustering_overgrow_batch_test_cases.txt (generated by
// generate_clustering_overgrow_batch_test_cases.py), runs ClusteringOvgBatch
// for each test case, and asserts that active_valid_clusters match the Python
// reference exactly in:
//   - which cluster_ids are active and valid
//   - fault_nodes and check_nodes (as sorted sets)
//   - fault_order and check_order (insertion-ordered lists — determines RREF column order)
//   - rref.n_checks, rref.n_bits, rref.pivot_map, rref.s_prime
//   - rref.Z (null-space basis vectors, in order)
//   - rref.is_valid()
//
// Build (from src/):
//   g++ -std=c++17 -O2 -mavx2 -Wall \
//       test_accross_python_cplus/test_clustering_overgrow_batch_vs_python.cpp \
//       clustering_overgrow_batch.cpp incremental_rref.cpp gf2matrix.cpp \
//       -o test_ogb_cross
//   ./test_ogb_cross [path/to/clustering_overgrow_batch_test_cases.txt]
// Default path: test_accross_python_cplus/clustering_overgrow_batch_test_cases.txt

#include "../clustering_overgrow_batch.hpp"

#include <algorithm>
#include <cassert>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Expected state structures
// ---------------------------------------------------------------------------

struct ExpectedCluster {
    int              cluster_id;
    std::vector<int> fault_nodes;   // sorted
    std::vector<int> check_nodes;   // sorted
    std::vector<int> fault_order;   // cluster_fault_idx_to_pcm_fault_idx
    std::vector<int> check_order;   // cluster_check_idx_to_pcm_check_idx
    int              n_checks = 0;
    int              n_bits   = 0;
    std::vector<int>     pivot_map;
    std::vector<uint8_t> s_prime;
    std::vector<std::vector<uint8_t>> Z;
    int is_valid = 0;
};

struct TestSpec {
    std::string name;
    int over_grow_step = 0;
    int bits_per_step  = 1;
    int n_det   = 0;
    int n_fault = 0;
    std::vector<std::vector<int>> check_to_faults;
    std::vector<std::vector<int>> fault_to_checks;
    std::vector<double>           weights;
    std::vector<uint8_t>          syndrome;
    int n_active_valid = 0;
    std::vector<ExpectedCluster>  clusters;   // in cluster_id order
};

// ---------------------------------------------------------------------------
// Parse helpers
// ---------------------------------------------------------------------------

static std::vector<int> read_n_ints(std::istringstream& ss, int n)
{
    std::vector<int> v(n);
    for (int i = 0; i < n; ++i) ss >> v[i];
    return v;
}

static std::vector<uint8_t> read_n_bytes(std::istringstream& ss, int n)
{
    std::vector<uint8_t> v(n);
    for (int i = 0; i < n; ++i) { int x; ss >> x; v[i] = static_cast<uint8_t>(x); }
    return v;
}

static std::vector<int> read_adj(std::istringstream& ss)
{
    int n; ss >> n;
    return read_n_ints(ss, n);
}

// ---------------------------------------------------------------------------
// Parse the test-case file into TestSpec objects.
// ---------------------------------------------------------------------------

static std::vector<TestSpec> parse_file(const std::string& path)
{
    std::ifstream fin(path);
    if (!fin) {
        fprintf(stderr, "Cannot open %s\n", path.c_str());
        std::exit(1);
    }

    std::vector<TestSpec> specs;
    TestSpec*         cur    = nullptr;
    ExpectedCluster*  cur_cl = nullptr;
    int ctf_idx    = 0;
    int ftc_idx    = 0;
    int z_remaining = 0;

    std::string line;
    while (std::getline(fin, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream ss(line);
        std::string kw; ss >> kw;

        if (kw == "TEST") {
            specs.emplace_back();
            cur    = &specs.back();
            cur_cl = nullptr;
            ctf_idx = ftc_idx = z_remaining = 0;
            ss >> cur->name;
            continue;
        }
        if (!cur) continue;
        if (kw == "ENDTEST") { cur = nullptr; continue; }

        // ---- Run parameters ----
        if (kw == "OVER_GROW_STEP") { ss >> cur->over_grow_step; continue; }
        if (kw == "BITS_PER_STEP")  { ss >> cur->bits_per_step;  continue; }

        // ---- Input fields ----
        if (kw == "NDET") {
            ss >> cur->n_det;
            cur->check_to_faults.resize(cur->n_det);
            continue;
        }
        if (kw == "NFAULT") {
            ss >> cur->n_fault;
            cur->fault_to_checks.resize(cur->n_fault);
            cur->weights.resize(cur->n_fault);
            continue;
        }
        if (kw == "CTF") { cur->check_to_faults[ctf_idx++] = read_adj(ss); continue; }
        if (kw == "FTC") { cur->fault_to_checks[ftc_idx++] = read_adj(ss); continue; }
        if (kw == "WEIGHTS") {
            for (int j = 0; j < cur->n_fault; ++j) ss >> cur->weights[j];
            continue;
        }
        if (kw == "SYNDROME") {
            cur->syndrome = read_n_bytes(ss, cur->n_det);
            continue;
        }

        // ---- Expected output ----
        if (kw == "NACTIVE_VALID") { ss >> cur->n_active_valid; continue; }

        if (kw == "CLUSTER") {
            cur->clusters.emplace_back();
            cur_cl      = &cur->clusters.back();
            z_remaining = 0;
            ss >> cur_cl->cluster_id;
            continue;
        }
        if (kw == "ENDCLUSTER") { cur_cl = nullptr; continue; }
        if (!cur_cl) continue;

        if (kw == "FAULT_NODES") { cur_cl->fault_nodes = read_adj(ss); continue; }
        if (kw == "CHECK_NODES") { cur_cl->check_nodes = read_adj(ss); continue; }
        if (kw == "FAULT_ORDER") { cur_cl->fault_order = read_adj(ss); continue; }
        if (kw == "CHECK_ORDER") { cur_cl->check_order = read_adj(ss); continue; }
        if (kw == "NCHECKS")    { ss >> cur_cl->n_checks; continue; }
        if (kw == "NBITS")      { ss >> cur_cl->n_bits;   continue; }
        if (kw == "PIVOT_MAP")  {
            cur_cl->pivot_map = read_n_ints(ss, cur_cl->n_checks); continue;
        }
        if (kw == "SPRIME") {
            cur_cl->s_prime = read_n_bytes(ss, cur_cl->n_checks); continue;
        }
        if (kw == "ZCOUNT")     { ss >> z_remaining; continue; }
        if (kw == "Z") {
            cur_cl->Z.push_back(read_n_bytes(ss, cur_cl->n_bits));
            --z_remaining;
            continue;
        }
        if (kw == "ISVALID") { ss >> cur_cl->is_valid; continue; }
    }
    return specs;
}

// ---------------------------------------------------------------------------
// Compare C++ output against expected values; abort on any mismatch.
// ---------------------------------------------------------------------------

static void check_result(const TestSpec& spec, const ClusteringOvgBatch& eng)
{
    const auto& avc = eng.active_valid_clusters;

    auto fail2 = [&](const std::string& msg) {
        fprintf(stderr, "FAIL [%s]: %s\n", spec.name.c_str(), msg.c_str());
        std::abort();
    };

    if ((int)avc.size() != spec.n_active_valid)
        fail2("n_active_valid=" + std::to_string(avc.size()) +
              " expected=" + std::to_string(spec.n_active_valid));

    for (const auto& exp : spec.clusters) {
        const int cid = exp.cluster_id;

        auto it = avc.find(cid);
        if (it == avc.end())
            fail2("cluster_id " + std::to_string(cid) + " missing");

        const ClusterStateOGB*  cl   = it->second;
        const IncrementalRREF&  rref = cl->rref;

        // fault_nodes (sorted set comparison)
        {
            std::vector<int> got(cl->fault_nodes.begin(), cl->fault_nodes.end());
            std::sort(got.begin(), got.end());
            if (got != exp.fault_nodes)
                fail2("cluster " + std::to_string(cid) + ": fault_nodes mismatch");
        }

        // check_nodes (sorted set comparison)
        {
            std::vector<int> got(cl->check_nodes.begin(), cl->check_nodes.end());
            std::sort(got.begin(), got.end());
            if (got != exp.check_nodes)
                fail2("cluster " + std::to_string(cid) + ": check_nodes mismatch");
        }

        // fault_order (insertion order — determines RREF column ordering)
        if (cl->cluster_fault_idx_to_pcm_fault_idx != exp.fault_order)
            fail2("cluster " + std::to_string(cid) + ": fault_order mismatch");

        // check_order (insertion order — determines RREF row ordering)
        if (cl->cluster_check_idx_to_pcm_check_idx != exp.check_order)
            fail2("cluster " + std::to_string(cid) + ": check_order mismatch");

        // n_checks / n_bits
        if (rref.n_checks != exp.n_checks)
            fail2("cluster " + std::to_string(cid) + ": n_checks=" +
                  std::to_string(rref.n_checks) + " expected=" +
                  std::to_string(exp.n_checks));

        if (rref.n_bits != exp.n_bits)
            fail2("cluster " + std::to_string(cid) + ": n_bits=" +
                  std::to_string(rref.n_bits) + " expected=" +
                  std::to_string(exp.n_bits));

        // pivot_map
        for (int i = 0; i < exp.n_checks; ++i) {
            if (rref.pivot_map[i] != exp.pivot_map[i])
                fail2("cluster " + std::to_string(cid) + ": pivot_map[" +
                      std::to_string(i) + "]=" + std::to_string(rref.pivot_map[i]) +
                      " expected=" + std::to_string(exp.pivot_map[i]));
        }

        // s_prime
        for (int i = 0; i < exp.n_checks; ++i) {
            if (rref.s_prime[i] != exp.s_prime[i])
                fail2("cluster " + std::to_string(cid) + ": s_prime[" +
                      std::to_string(i) + "]=" + std::to_string((int)rref.s_prime[i]) +
                      " expected=" + std::to_string((int)exp.s_prime[i]));
        }

        // Z count
        if ((int)rref.Z.size() != (int)exp.Z.size())
            fail2("cluster " + std::to_string(cid) + ": |Z|=" +
                  std::to_string(rref.Z.size()) + " expected=" +
                  std::to_string(exp.Z.size()));

        // Z vectors (in order)
        for (int k = 0; k < (int)exp.Z.size(); ++k) {
            if (rref.Z[k] != exp.Z[k])
                fail2("cluster " + std::to_string(cid) + ": Z[" +
                      std::to_string(k) + "] mismatch");
        }

        // is_valid
        const int got_v = rref.is_valid() ? 1 : 0;
        if (got_v != exp.is_valid)
            fail2("cluster " + std::to_string(cid) + ": is_valid=" +
                  std::to_string(got_v) + " expected=" +
                  std::to_string(exp.is_valid));
    }
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

int main(int argc, char** argv)
{
    std::string path =
        "test_accross_python_cplus/clustering_overgrow_batch_test_cases.txt";
    if (argc >= 2) path = argv[1];

    auto specs = parse_file(path);
    printf("Running %zu tests from %s\n", specs.size(), path.c_str());

    int n_passed = 0;
    for (const auto& spec : specs) {
        // Construct with no logical matrix (test cases don't use L).
        ClusteringOvgBatch eng(
            spec.n_det, spec.n_fault,
            spec.check_to_faults,
            spec.fault_to_checks,
            spec.weights
        );
        eng.run(spec.syndrome, spec.over_grow_step, spec.bits_per_step);
        check_result(spec, eng);
        printf("  PASSED: %s\n", spec.name.c_str());
        ++n_passed;
    }

    printf("\nAll %d tests passed.\n", n_passed);
    return 0;
}
