// test_prior_gap_estimator_vs_python.cpp
//
// Cross-language validation: C++ PriorGapEstimator vs Python reference.
//
// Reads prior_gap_estimator_test_cases.txt (generated by
// generate_prior_gap_estimator_test_cases.py), runs PriorGapEstimator::execute
// for each test case, and asserts:
//   - gap matches within tolerance 1e-10 (or both infinite with same sign)
//   - nonzero_count matches exactly
//   - overall_logical_flip matches byte-for-byte (when decode=true)
//
// Build (from src/):
//   g++ -std=c++17 -O2 -mavx2 -Wall \
//       test_accross_python_cplus/test_prior_gap_estimator_vs_python.cpp \
//       prior_gap_estimator.cpp clustering_overgrow_batch.cpp \
//       incremental_rref.cpp gf2matrix.cpp \
//       -o test_gap_est_cross
//   ./test_gap_est_cross [path/to/prior_gap_estimator_test_cases.txt]
//
// Default path: test_accross_python_cplus/prior_gap_estimator_test_cases.txt

#include "../prior_gap_estimator.hpp"

#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <limits>
#include <sstream>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Test-case structure
// ---------------------------------------------------------------------------

struct TestSpec {
    std::string name;

    // run parameters
    std::string gap_type_str  = "binary";
    std::string aggregate_str = "min";
    bool asb    = false;
    bool decode = false;
    int  over_grow_step = 0;
    int  bits_per_step  = 1;

    // PCM
    int n_det    = 0;
    int n_fault  = 0;
    int n_logical = 0;
    std::vector<std::vector<int>>    check_to_faults;
    std::vector<std::vector<int>>    fault_to_checks;
    std::vector<double>              weights;
    std::vector<std::vector<uint8_t>> L_rows;   // n_logical rows, each length n_fault

    // input
    std::vector<uint8_t> syndrome;

    // expected outputs
    double               expected_gap          = 0.0;
    int                  expected_nonzero      = 0;
    std::vector<uint8_t> expected_flip;   // empty when decode=false or n_logical=0
};

// ---------------------------------------------------------------------------
// Parse helpers
// ---------------------------------------------------------------------------

static double parse_double(const std::string& s)
{
    if (s == "inf")  return  std::numeric_limits<double>::infinity();
    if (s == "-inf") return -std::numeric_limits<double>::infinity();
    return std::stod(s);
}

static std::vector<int> read_adj(std::istringstream& ss)
{
    int n; ss >> n;
    std::vector<int> v(n);
    for (int i = 0; i < n; ++i) ss >> v[i];
    return v;
}

static std::vector<uint8_t> read_n_bytes(std::istringstream& ss, int n)
{
    std::vector<uint8_t> v(n);
    for (int i = 0; i < n; ++i) { int x; ss >> x; v[i] = static_cast<uint8_t>(x); }
    return v;
}

// ---------------------------------------------------------------------------
// Parse the test-case file
// ---------------------------------------------------------------------------

static std::vector<TestSpec> parse_file(const std::string& path)
{
    std::ifstream fin(path);
    if (!fin) {
        fprintf(stderr, "Cannot open %s\n", path.c_str());
        std::exit(1);
    }

    std::vector<TestSpec> specs;
    TestSpec* cur    = nullptr;
    int ctf_idx = 0, ftc_idx = 0;

    std::string line;
    while (std::getline(fin, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream ss(line);
        std::string kw; ss >> kw;

        if (kw == "TEST") {
            specs.emplace_back();
            cur = &specs.back();
            ctf_idx = ftc_idx = 0;
            ss >> cur->name;
            continue;
        }
        if (!cur) continue;
        if (kw == "ENDTEST") { cur = nullptr; continue; }

        // run parameters
        if (kw == "GAP_TYPE")      { ss >> cur->gap_type_str;  continue; }
        if (kw == "AGGREGATE")     { ss >> cur->aggregate_str; continue; }
        if (kw == "ASB")           { int v; ss >> v; cur->asb    = (v != 0); continue; }
        if (kw == "DECODE")        { int v; ss >> v; cur->decode = (v != 0); continue; }
        if (kw == "OVER_GROW_STEP"){ ss >> cur->over_grow_step; continue; }
        if (kw == "BITS_PER_STEP") { ss >> cur->bits_per_step;  continue; }

        // PCM
        if (kw == "NDET") {
            ss >> cur->n_det;
            cur->check_to_faults.resize(cur->n_det);
            continue;
        }
        if (kw == "NFAULT") {
            ss >> cur->n_fault;
            cur->fault_to_checks.resize(cur->n_fault);
            cur->weights.resize(cur->n_fault);
            continue;
        }
        if (kw == "NLOGICAL") { ss >> cur->n_logical; continue; }
        if (kw == "CTF") { cur->check_to_faults[ctf_idx++] = read_adj(ss); continue; }
        if (kw == "FTC") { cur->fault_to_checks[ftc_idx++] = read_adj(ss); continue; }
        if (kw == "WEIGHTS") {
            for (int j = 0; j < cur->n_fault; ++j) ss >> cur->weights[j];
            continue;
        }
        if (kw == "L_ROW") {
            cur->L_rows.push_back(read_n_bytes(ss, cur->n_fault));
            continue;
        }
        if (kw == "SYNDROME") {
            cur->syndrome = read_n_bytes(ss, cur->n_det);
            continue;
        }

        // expected outputs
        if (kw == "EXPECTED_GAP") {
            std::string sv; ss >> sv;
            cur->expected_gap = parse_double(sv);
            continue;
        }
        if (kw == "EXPECTED_NONZERO") { ss >> cur->expected_nonzero; continue; }
        if (kw == "EXPECTED_FLIP") {
            // Read remaining tokens on the line as uint8 flip values.
            cur->expected_flip.clear();
            int v;
            while (ss >> v) cur->expected_flip.push_back(static_cast<uint8_t>(v));
            continue;
        }
    }
    return specs;
}

// ---------------------------------------------------------------------------
// Gap-type / aggregate string → int
// ---------------------------------------------------------------------------

static int gap_type_int(const std::string& s)
{
    if (s == "binary")       return GAP_BINARY;
    if (s == "hamming")      return GAP_HAMMING;
    if (s == "prior_weight") return GAP_PRIOR;
    if (s == "weight_diff")  return GAP_WEIGHT_DIFF;
    fprintf(stderr, "Unknown gap_type: %s\n", s.c_str());
    std::exit(1);
}

static int aggregate_int(const std::string& s)
{
    if (s == "min") return AGG_MIN;
    if (s == "sum") return AGG_SUM;
    fprintf(stderr, "Unknown aggregate: %s\n", s.c_str());
    std::exit(1);
}

// ---------------------------------------------------------------------------
// Comparison helpers
// ---------------------------------------------------------------------------

static bool gap_ok(double got, double expected, double tol = 1e-10)
{
    if (std::isinf(expected) && std::isinf(got))
        return (got > 0) == (expected > 0);
    if (std::isinf(expected) || std::isinf(got))
        return false;
    return std::abs(got - expected) <= tol;
}

// ---------------------------------------------------------------------------
// Run all test cases
// ---------------------------------------------------------------------------

int main(int argc, char** argv)
{
    const std::string default_path =
        "test_accross_python_cplus/prior_gap_estimator_test_cases.txt";
    std::string path = (argc > 1) ? argv[1] : default_path;

    auto specs = parse_file(path);
    if (specs.empty()) {
        fprintf(stderr, "No test cases found in %s\n", path.c_str());
        return 1;
    }

    int passed = 0, failed = 0;

    for (const TestSpec& spec : specs) {

        // Build PriorGapEstimator from parsed PCM data.
        PriorGapEstimator est(
            spec.n_det, spec.n_fault,
            spec.check_to_faults,
            spec.fault_to_checks,
            spec.weights,
            spec.n_logical,
            spec.L_rows
        );

        // Run execute.
        ExecuteResult res = est.execute(
            spec.syndrome,
            gap_type_int(spec.gap_type_str),
            aggregate_int(spec.aggregate_str),
            spec.over_grow_step,
            spec.bits_per_step,
            spec.asb,
            spec.decode
        );

        // Check gap.
        bool gap_pass = gap_ok(res.gap, spec.expected_gap);

        // Check nonzero_count.
        bool nz_pass = (res.nonzero_count == spec.expected_nonzero);

        // Check flip (only when decode=true and n_logical > 0).
        bool flip_pass = true;
        if (spec.decode && spec.n_logical > 0) {
            if (res.overall_logical_flip.size() != spec.expected_flip.size()) {
                flip_pass = false;
            } else {
                for (size_t k = 0; k < spec.expected_flip.size(); ++k)
                    if (res.overall_logical_flip[k] != spec.expected_flip[k]) {
                        flip_pass = false;
                        break;
                    }
            }
        }

        bool ok = gap_pass && nz_pass && flip_pass;

        if (ok) {
            printf("PASS  %s\n", spec.name.c_str());
            ++passed;
        } else {
            printf("FAIL  %s\n", spec.name.c_str());
            if (!gap_pass)
                printf("      gap:    got %.17g  expected %.17g\n",
                       res.gap, spec.expected_gap);
            if (!nz_pass)
                printf("      nonzero: got %d  expected %d\n",
                       res.nonzero_count, spec.expected_nonzero);
            if (!flip_pass) {
                printf("      flip:   got [");
                for (size_t k = 0; k < res.overall_logical_flip.size(); ++k)
                    printf("%d%s", res.overall_logical_flip[k],
                           k + 1 < res.overall_logical_flip.size() ? "," : "");
                printf("]  expected [");
                for (size_t k = 0; k < spec.expected_flip.size(); ++k)
                    printf("%d%s", spec.expected_flip[k],
                           k + 1 < spec.expected_flip.size() ? "," : "");
                printf("]\n");
            }
            ++failed;
        }
    }

    printf("\n%d / %d passed\n", passed, passed + failed);
    return (failed == 0) ? 0 : 1;
}
