// Cross-language validation: C++ IncrementalRREF vs Python reference.
//
// Reads rref_test_cases.txt (generated by generate_rref_test_cases.py),
// replays every operation using the C++ IncrementalRREF, and asserts that
// n_checks, n_bits, pivot_map, s_prime, Z, and is_valid() match the Python
// reference values exactly.
//
// Build (from the src/ directory):
//   g++ -std=c++17 -O2 -Wall
//       test_accross_python_cplus/test_rref_vs_python.cpp
//       incremental_rref.cpp -o test_rref_cross
//   ./test_rref_cross [path/to/rref_test_cases.txt]
// Default path: test_accross_python_cplus/rref_test_cases.txt

#include "../incremental_rref.hpp"

#include <cassert>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Parsing helpers
// ---------------------------------------------------------------------------

static std::vector<uint8_t> parse_bytes(std::istringstream& ss, int n)
{
    std::vector<uint8_t> v(n);
    for (int i = 0; i < n; ++i) {
        int x; ss >> x;
        v[i] = static_cast<uint8_t>(x);
    }
    return v;
}

// ---------------------------------------------------------------------------
// Recompute s_prime = T @ s  (mod 2)  — used for SET_S.
// ---------------------------------------------------------------------------
static void apply_set_s(IncrementalRREF& rref,
                        const std::vector<uint8_t>& s_new)
{
    rref.s = s_new;
    auto s_packed = GF2Matrix::pack_vec(s_new);
    rref.s_prime.resize(rref.n_checks);
    rref.T.matvec(s_packed.data(), rref.s_prime.data());
}

// ---------------------------------------------------------------------------
// Apply a single operation line (keyword already consumed from `ss`).
// ---------------------------------------------------------------------------
static void apply_op(const std::string& keyword,
                     std::istringstream& ss,
                     IncrementalRREF& rref)
{
    if (keyword == "ADD_EXTRA") {
        int h_len; ss >> h_len;
        auto h = parse_bytes(ss, h_len);
        int s_len; ss >> s_len;
        auto s_ex = parse_bytes(ss, s_len);
        rref.add_column(h, s_ex);
    } else if (keyword == "ADD") {
        int h_len; ss >> h_len;
        auto h = parse_bytes(ss, h_len);
        rref.add_column(h);
    } else if (keyword == "SET_S") {
        int n; ss >> n;
        auto s_new = parse_bytes(ss, n);
        apply_set_s(rref, s_new);
    } else {
        throw std::runtime_error("Unknown op keyword: " + keyword);
    }
}

// ---------------------------------------------------------------------------
// Compare C++ state vs expected values from the text file.
// ---------------------------------------------------------------------------
struct ExpectedState {
    int n_checks;
    int n_bits;
    std::vector<int>     pivot_map;   // -1 means no pivot
    std::vector<uint8_t> s_prime;
    std::vector<std::vector<uint8_t>> Z;
    int is_valid;  // 0 or 1
};

static void check_state(const std::string& test_name,
                        const IncrementalRREF& rref,
                        const ExpectedState& exp)
{
    // n_checks
    if (rref.n_checks != exp.n_checks) {
        fprintf(stderr, "FAIL [%s]: n_checks=%d expected=%d\n",
                test_name.c_str(), rref.n_checks, exp.n_checks);
        std::abort();
    }
    // n_bits
    if (rref.n_bits != exp.n_bits) {
        fprintf(stderr, "FAIL [%s]: n_bits=%d expected=%d\n",
                test_name.c_str(), rref.n_bits, exp.n_bits);
        std::abort();
    }
    // pivot_map
    if ((int)rref.pivot_map.size() != rref.n_checks) {
        fprintf(stderr, "FAIL [%s]: pivot_map.size()=%zu expected %d\n",
                test_name.c_str(), rref.pivot_map.size(), rref.n_checks);
        std::abort();
    }
    for (int i = 0; i < rref.n_checks; ++i) {
        if (rref.pivot_map[i] != exp.pivot_map[i]) {
            fprintf(stderr, "FAIL [%s]: pivot_map[%d]=%d expected=%d\n",
                    test_name.c_str(), i, rref.pivot_map[i], exp.pivot_map[i]);
            std::abort();
        }
    }
    // s_prime
    for (int i = 0; i < rref.n_checks; ++i) {
        if (rref.s_prime[i] != exp.s_prime[i]) {
            fprintf(stderr, "FAIL [%s]: s_prime[%d]=%d expected=%d\n",
                    test_name.c_str(), i, (int)rref.s_prime[i], (int)exp.s_prime[i]);
            std::abort();
        }
    }
    // Z count
    if ((int)rref.Z.size() != (int)exp.Z.size()) {
        fprintf(stderr, "FAIL [%s]: |Z|=%zu expected=%zu\n",
                test_name.c_str(), rref.Z.size(), exp.Z.size());
        std::abort();
    }
    // Z vectors (in order)
    for (int k = 0; k < (int)exp.Z.size(); ++k) {
        if (rref.Z[k].size() != exp.Z[k].size()) {
            fprintf(stderr, "FAIL [%s]: Z[%d].size()=%zu expected=%zu\n",
                    test_name.c_str(), k, rref.Z[k].size(), exp.Z[k].size());
            std::abort();
        }
        for (int j = 0; j < (int)exp.Z[k].size(); ++j) {
            if (rref.Z[k][j] != exp.Z[k][j]) {
                fprintf(stderr, "FAIL [%s]: Z[%d][%d]=%d expected=%d\n",
                        test_name.c_str(), k, j,
                        (int)rref.Z[k][j], (int)exp.Z[k][j]);
                std::abort();
            }
        }
    }
    // is_valid
    int got_valid = rref.is_valid() ? 1 : 0;
    if (got_valid != exp.is_valid) {
        fprintf(stderr, "FAIL [%s]: is_valid=%d expected=%d\n",
                test_name.c_str(), got_valid, exp.is_valid);
        std::abort();
    }
}

// ---------------------------------------------------------------------------
// Per-test specification collected during parsing.
// Merge tests record ops for c1/c2 separately; the merge is applied at
// execution time so the comparison is straightforward.
// ---------------------------------------------------------------------------

struct TestSpec {
    std::string name;
    bool is_merge;

    // Plain test
    std::vector<std::pair<std::string, std::string>> plain_ops;  // (kw, rest_of_line)

    // Merge test
    std::vector<std::pair<std::string, std::string>> c1_ops;
    std::vector<std::pair<std::string, std::string>> c2_ops;
    std::vector<std::vector<uint8_t>> conn_edges;

    ExpectedState exp;
    // mid-test validity checks: (after_op_index, expected_valid)
    // Indexed relative to the op list they belong to.
    // For simplicity, store as a parallel list of (op_idx_plain, expected)
    // collected in order.
    struct ValidCheck { int after_op; int expected; };
    std::vector<ValidCheck> valid_checks;
};

static int run_tests_v2(const std::string& path)
{
    std::ifstream fin(path);
    if (!fin) {
        fprintf(stderr, "Cannot open %s\n", path.c_str());
        return 1;
    }

    int n_passed = 0;

    // Parse the whole file into TestSpec objects, then execute each.
    std::vector<TestSpec> specs;

    TestSpec* cur = nullptr;
    bool reading_exp = false;
    int z_remaining = 0;
    int plain_op_count = 0;  // tracks how many OP lines we've seen (for CHECK_ISVALID)

    std::string line;
    while (std::getline(fin, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream ss(line);
        std::string kw; ss >> kw;

        if (kw == "TEST") {
            specs.emplace_back();
            cur = &specs.back();
            ss >> cur->name;
            cur->is_merge = false;
            reading_exp = false;
            z_remaining = 0;
            plain_op_count = 0;
            continue;
        }
        if (!cur) continue;

        if (kw == "ENDTEST") {
            cur = nullptr;
            reading_exp = false;
            continue;
        }

        // State block
        if (kw == "NCHECKS") {
            reading_exp = true;
            ss >> cur->exp.n_checks;
            cur->exp.pivot_map.resize(cur->exp.n_checks, -1);
            cur->exp.s_prime.resize(cur->exp.n_checks, 0);
            continue;
        }
        if (reading_exp) {
            if (kw == "NBITS") {
                ss >> cur->exp.n_bits;
            } else if (kw == "PIVOT_MAP") {
                for (int i = 0; i < cur->exp.n_checks; ++i)
                    ss >> cur->exp.pivot_map[i];
            } else if (kw == "SPRIME") {
                for (int i = 0; i < cur->exp.n_checks; ++i) {
                    int v; ss >> v;
                    cur->exp.s_prime[i] = static_cast<uint8_t>(v);
                }
            } else if (kw == "ZCOUNT") {
                ss >> z_remaining;
            } else if (kw == "Z") {
                std::vector<uint8_t> z(cur->exp.n_bits);
                for (int j = 0; j < cur->exp.n_bits; ++j) {
                    int v; ss >> v; z[j] = static_cast<uint8_t>(v);
                }
                cur->exp.Z.push_back(std::move(z));
                --z_remaining;
            } else if (kw == "ISVALID") {
                ss >> cur->exp.is_valid;
                reading_exp = false;
            }
            continue;
        }

        // CHECK_ISVALID: immediate validity check at this point in the op stream
        if (kw == "CHECK_ISVALID") {
            int v; ss >> v;
            cur->valid_checks.push_back({plain_op_count, v});
            continue;
        }

        // OP lines (plain test)
        if (kw == "OP") {
            std::string rest;
            std::getline(ss, rest);
            cur->plain_ops.push_back({"OP", rest});
            ++plain_op_count;
            continue;
        }

        // C1 / C2 / CONNECT lines (merge test)
        if (kw == "C1") {
            cur->is_merge = true;
            std::string rest;
            std::getline(ss, rest);
            cur->c1_ops.push_back({"C1", rest});
            continue;
        }
        if (kw == "C2") {
            cur->is_merge = true;
            std::string rest;
            std::getline(ss, rest);
            cur->c2_ops.push_back({"C2", rest});
            continue;
        }
        if (kw == "CONNECT") {
            cur->is_merge = true;
            int h_len; ss >> h_len;
            auto h = parse_bytes(ss, h_len);
            cur->conn_edges.push_back(std::move(h));
            continue;
        }
    }

    // -----------------------------------------------------------------------
    // Execute each test
    // -----------------------------------------------------------------------
    printf("Running %zu tests from %s\n", specs.size(), path.c_str());

    for (auto& spec : specs) {
        if (spec.is_merge) {
            // Build c1
            IncrementalRREF c1;
            for (auto& [ignored, rest] : spec.c1_ops) {
                std::istringstream ls(rest);
                std::string op_kw; ls >> op_kw;
                apply_op(op_kw, ls, c1);
            }
            // Build c2
            IncrementalRREF c2;
            for (auto& [ignored, rest] : spec.c2_ops) {
                std::istringstream ls(rest);
                std::string op_kw; ls >> op_kw;
                apply_op(op_kw, ls, c2);
            }
            // Merge
            IncrementalRREF merged = IncrementalRREF::merge(c1, c2, spec.conn_edges);
            check_state(spec.name, merged, spec.exp);
            merged.verify();
        } else {
            // Plain test
            IncrementalRREF rref;
            int op_idx = 0;
            int check_ptr = 0;
            int n_checks = static_cast<int>(spec.valid_checks.size());

            for (auto& [kw, rest] : spec.plain_ops) {
                std::istringstream ls(rest);
                std::string op_kw; ls >> op_kw;
                apply_op(op_kw, ls, rref);
                ++op_idx;

                // Run any CHECK_ISVALID that fire at this op index
                while (check_ptr < n_checks &&
                       spec.valid_checks[check_ptr].after_op == op_idx) {
                    int expected_v = spec.valid_checks[check_ptr].expected;
                    int got_v = rref.is_valid() ? 1 : 0;
                    if (got_v != expected_v) {
                        fprintf(stderr,
                                "FAIL [%s]: CHECK_ISVALID after op %d: got=%d expected=%d\n",
                                spec.name.c_str(), op_idx, got_v, expected_v);
                        std::abort();
                    }
                    ++check_ptr;
                }
            }

            // Run any remaining CHECK_ISVALID (after all ops)
            while (check_ptr < n_checks) {
                int expected_v = spec.valid_checks[check_ptr].expected;
                int got_v = rref.is_valid() ? 1 : 0;
                if (got_v != expected_v) {
                    fprintf(stderr,
                            "FAIL [%s]: CHECK_ISVALID (trailing): got=%d expected=%d\n",
                            spec.name.c_str(), got_v, expected_v);
                    std::abort();
                }
                ++check_ptr;
            }

            check_state(spec.name, rref, spec.exp);
            rref.verify();
        }

        printf("  PASSED: %s\n", spec.name.c_str());
        ++n_passed;
    }

    return n_passed;
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

int main(int argc, char** argv)
{
    // Determine path to test cases file.
    std::string path = "test_accross_python_cplus/rref_test_cases.txt";
    if (argc >= 2) path = argv[1];

    int n_passed = run_tests_v2(path);
    printf("\nAll %d tests passed.\n", n_passed);
    return 0;
}
