// Cross-language validation: C++ Clustering vs Python reference.
//
// Reads clustering_test_cases.txt (generated by generate_clustering_test_cases.py),
// constructs and runs the C++ Clustering engine for each test case, and asserts
// that the active_valid_clusters match the Python reference exactly in:
//   - which cluster_ids are active and valid
//   - fault_nodes and check_nodes (as sorted sets)
//   - fault_order and check_order (insertion-ordered lists — determines RREF column order)
//   - rref.n_checks, rref.n_bits, rref.pivot_map, rref.s_prime
//   - rref.Z (null-space basis vectors, in order)
//   - rref.is_valid()
//
// Build (from src/):
//   g++ -std=c++17 -O2 -mavx2 -Wall \
//       test_accross_python_cplus/test_clustering_vs_python.cpp \
//       clustering.cpp incremental_rref.cpp gf2matrix.cpp \
//       -o test_clustering_cross
//   ./test_clustering_cross [path/to/clustering_test_cases.txt]

#include "../clustering.hpp"

#include <algorithm>
#include <cassert>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Expected state structures (populated from the text file)
// ---------------------------------------------------------------------------

struct ExpectedCluster {
    int              cluster_id;
    std::vector<int> fault_nodes;   // sorted list
    std::vector<int> check_nodes;   // sorted list
    std::vector<int> fault_order;   // cluster_fault_idx_to_pcm_fault_idx
    std::vector<int> check_order;   // cluster_check_idx_to_pcm_check_idx
    int              n_checks = 0;
    int              n_bits   = 0;
    std::vector<int>     pivot_map;
    std::vector<uint8_t> s_prime;
    std::vector<std::vector<uint8_t>> Z;
    int is_valid = 0;
};

struct TestSpec {
    std::string name;
    int n_det   = 0;
    int n_fault = 0;
    std::vector<std::vector<int>> check_to_faults;
    std::vector<std::vector<int>> fault_to_checks;
    std::vector<double>           weights;
    std::vector<uint8_t>          syndrome;
    int n_active_valid = 0;
    std::vector<ExpectedCluster>  clusters;  // sorted by cluster_id
};

// ---------------------------------------------------------------------------
// Parse helpers
// ---------------------------------------------------------------------------

// Read N integers from ss.
static std::vector<int> read_n_ints(std::istringstream& ss, int n)
{
    std::vector<int> v(n);
    for (int i = 0; i < n; ++i) ss >> v[i];
    return v;
}

// Read N bytes (as ints) from ss.
static std::vector<uint8_t> read_n_bytes(std::istringstream& ss, int n)
{
    std::vector<uint8_t> v(n);
    for (int i = 0; i < n; ++i) { int x; ss >> x; v[i] = static_cast<uint8_t>(x); }
    return v;
}

// Read count-prefixed adjacency: "N idx0 idx1 ... idx_{N-1}".
static std::vector<int> read_adj(std::istringstream& ss)
{
    int n; ss >> n;
    return read_n_ints(ss, n);
}

// ---------------------------------------------------------------------------
// Parse the full test file into TestSpec objects.
// ---------------------------------------------------------------------------

static std::vector<TestSpec> parse_file(const std::string& path)
{
    std::ifstream fin(path);
    if (!fin) {
        fprintf(stderr, "Cannot open %s\n", path.c_str());
        std::exit(1);
    }

    std::vector<TestSpec>  specs;
    TestSpec*              cur    = nullptr;
    ExpectedCluster*       cur_cl = nullptr;
    int ctf_idx    = 0;
    int ftc_idx    = 0;
    int z_remaining = 0;

    std::string line;
    while (std::getline(fin, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream ss(line);
        std::string kw; ss >> kw;

        // ---- Top-level test boundaries ----
        if (kw == "TEST") {
            specs.emplace_back();
            cur    = &specs.back();
            cur_cl = nullptr;
            ctf_idx = ftc_idx = z_remaining = 0;
            ss >> cur->name;
            continue;
        }
        if (!cur) continue;
        if (kw == "ENDTEST") { cur = nullptr; continue; }

        // ---- Input fields ----
        if (kw == "NDET") {
            ss >> cur->n_det;
            cur->check_to_faults.resize(cur->n_det);
            continue;
        }
        if (kw == "NFAULT") {
            ss >> cur->n_fault;
            cur->fault_to_checks.resize(cur->n_fault);
            cur->weights.resize(cur->n_fault);
            continue;
        }
        if (kw == "CTF") { cur->check_to_faults[ctf_idx++] = read_adj(ss); continue; }
        if (kw == "FTC") { cur->fault_to_checks[ftc_idx++] = read_adj(ss); continue; }
        if (kw == "WEIGHTS") {
            for (int j = 0; j < cur->n_fault; ++j) ss >> cur->weights[j];
            continue;
        }
        if (kw == "SYNDROME") {
            cur->syndrome = read_n_bytes(ss, cur->n_det);
            continue;
        }

        // ---- Expected output fields ----
        if (kw == "NACTIVE_VALID") { ss >> cur->n_active_valid; continue; }

        if (kw == "CLUSTER") {
            cur->clusters.emplace_back();
            cur_cl      = &cur->clusters.back();
            z_remaining = 0;
            ss >> cur_cl->cluster_id;
            continue;
        }
        if (kw == "ENDCLUSTER") { cur_cl = nullptr; continue; }
        if (!cur_cl) continue;

        if (kw == "FAULT_NODES") { cur_cl->fault_nodes = read_adj(ss);  continue; }
        if (kw == "CHECK_NODES") { cur_cl->check_nodes = read_adj(ss);  continue; }
        if (kw == "FAULT_ORDER") { cur_cl->fault_order = read_adj(ss);  continue; }
        if (kw == "CHECK_ORDER") { cur_cl->check_order = read_adj(ss);  continue; }
        if (kw == "NCHECKS")    { ss >> cur_cl->n_checks; continue; }
        if (kw == "NBITS")      { ss >> cur_cl->n_bits;   continue; }
        if (kw == "PIVOT_MAP")  { cur_cl->pivot_map = read_n_ints (ss, cur_cl->n_checks); continue; }
        if (kw == "SPRIME")     { cur_cl->s_prime   = read_n_bytes(ss, cur_cl->n_checks); continue; }
        if (kw == "ZCOUNT")     { ss >> z_remaining; continue; }
        if (kw == "Z") {
            cur_cl->Z.push_back(read_n_bytes(ss, cur_cl->n_bits));
            --z_remaining;
            continue;
        }
        if (kw == "ISVALID")    { ss >> cur_cl->is_valid; continue; }
    }
    return specs;
}

// ---------------------------------------------------------------------------
// Compare C++ Clustering output against one TestSpec.
// ---------------------------------------------------------------------------

static void check_result(const TestSpec& spec, const Clustering& eng)
{
    const auto& avc = eng.active_valid_clusters;

    // Number of active valid clusters.
    if ((int)avc.size() != spec.n_active_valid) {
        fprintf(stderr, "FAIL [%s]: n_active_valid=%d expected=%d\n",
                spec.name.c_str(), (int)avc.size(), spec.n_active_valid);
        std::abort();
    }

    for (const auto& exp : spec.clusters) {
        const int cid = exp.cluster_id;

        auto it = avc.find(cid);
        if (it == avc.end()) {
            fprintf(stderr, "FAIL [%s]: cluster_id %d missing from active_valid_clusters\n",
                    spec.name.c_str(), cid);
            std::abort();
        }
        const ClusterState*    cl   = it->second;
        const IncrementalRREF& rref = cl->rref;

        // fault_nodes (order-independent set comparison via sorting).
        {
            std::vector<int> got(cl->fault_nodes.begin(), cl->fault_nodes.end());
            std::sort(got.begin(), got.end());
            if (got != exp.fault_nodes) {
                fprintf(stderr, "FAIL [%s] cluster %d: fault_nodes mismatch\n",
                        spec.name.c_str(), cid);
                std::abort();
            }
        }

        // check_nodes.
        {
            std::vector<int> got(cl->check_nodes.begin(), cl->check_nodes.end());
            std::sort(got.begin(), got.end());
            if (got != exp.check_nodes) {
                fprintf(stderr, "FAIL [%s] cluster %d: check_nodes mismatch\n",
                        spec.name.c_str(), cid);
                std::abort();
            }
        }

        // fault_order (insertion order — determines RREF column ordering).
        if (cl->cluster_fault_idx_to_pcm_fault_idx != exp.fault_order) {
            fprintf(stderr, "FAIL [%s] cluster %d: fault_order mismatch\n",
                    spec.name.c_str(), cid);
            std::abort();
        }

        // check_order.
        if (cl->cluster_check_idx_to_pcm_check_idx != exp.check_order) {
            fprintf(stderr, "FAIL [%s] cluster %d: check_order mismatch\n",
                    spec.name.c_str(), cid);
            std::abort();
        }

        // n_checks / n_bits.
        if (rref.n_checks != exp.n_checks) {
            fprintf(stderr, "FAIL [%s] cluster %d: n_checks=%d expected=%d\n",
                    spec.name.c_str(), cid, rref.n_checks, exp.n_checks);
            std::abort();
        }
        if (rref.n_bits != exp.n_bits) {
            fprintf(stderr, "FAIL [%s] cluster %d: n_bits=%d expected=%d\n",
                    spec.name.c_str(), cid, rref.n_bits, exp.n_bits);
            std::abort();
        }

        // pivot_map.
        for (int i = 0; i < exp.n_checks; ++i) {
            if (rref.pivot_map[i] != exp.pivot_map[i]) {
                fprintf(stderr, "FAIL [%s] cluster %d: pivot_map[%d]=%d expected=%d\n",
                        spec.name.c_str(), cid, i, rref.pivot_map[i], exp.pivot_map[i]);
                std::abort();
            }
        }

        // s_prime.
        for (int i = 0; i < exp.n_checks; ++i) {
            if (rref.s_prime[i] != exp.s_prime[i]) {
                fprintf(stderr, "FAIL [%s] cluster %d: s_prime[%d]=%d expected=%d\n",
                        spec.name.c_str(), cid, i,
                        (int)rref.s_prime[i], (int)exp.s_prime[i]);
                std::abort();
            }
        }

        // Z count.
        if ((int)rref.Z.size() != (int)exp.Z.size()) {
            fprintf(stderr, "FAIL [%s] cluster %d: |Z|=%zu expected=%zu\n",
                    spec.name.c_str(), cid, rref.Z.size(), exp.Z.size());
            std::abort();
        }

        // Z vectors (in order — both sides built by the same algorithm).
        for (int k = 0; k < (int)exp.Z.size(); ++k) {
            if (rref.Z[k] != exp.Z[k]) {
                fprintf(stderr, "FAIL [%s] cluster %d: Z[%d] mismatch\n",
                        spec.name.c_str(), cid, k);
                std::abort();
            }
        }

        // is_valid.
        const int got_v = rref.is_valid() ? 1 : 0;
        if (got_v != exp.is_valid) {
            fprintf(stderr, "FAIL [%s] cluster %d: is_valid=%d expected=%d\n",
                    spec.name.c_str(), cid, got_v, exp.is_valid);
            std::abort();
        }
    }
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

int main(int argc, char** argv)
{
    std::string path = "test_accross_python_cplus/clustering_test_cases.txt";
    if (argc >= 2) path = argv[1];

    auto specs = parse_file(path);
    printf("Running %zu tests from %s\n", specs.size(), path.c_str());

    int n_passed = 0;
    for (const auto& spec : specs) {
        Clustering eng(spec.n_det, spec.n_fault,
                       spec.check_to_faults,
                       spec.fault_to_checks,
                       spec.weights);
        eng.run(spec.syndrome);
        check_result(spec, eng);
        printf("  PASSED: %s\n", spec.name.c_str());
        ++n_passed;
    }

    printf("\nAll %d tests passed.\n", n_passed);
    return 0;
}
